[tool.poetry]
name = "speedstats"
version = "0.1.0"
description = "Internet Speed Statistic"
authors = ["Searge"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
getmac = "^0.9.0"
rich = "^14.1"
speedtest-cli = "^2.1.3"
urllib3 = "^2.0"


[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"

autopep8 = "^1.6.0"
mypy = "^1.0"
wemake-python-styleguide = "^0.16.1"

cyberbrain = "^0.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.nitpick]
style = [
  "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/flake8.toml",
  "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/isort.toml"
]
